import assert from "node:assert/strict";
import test from "node:test";
import { Decimal, MockExchangeRateProvider, MockMarketDataProvider, PricingEngine, analyzeMarketHistory, assessLiquidity, money, type MarketDataPoint, type PricingRuleVersion } from "../src/index.ts";

const now = new Date("2026-09-05T12:00:00.000Z");
const rule = (overrides: Partial<PricingRuleVersion["configuration"]> = {}): PricingRuleVersion => ({ id: "price-rule-v1", version: 1, effectiveFrom: now, configuration: { inventoryRiskMargin: Decimal.from("0.1"), orderMarkup: Decimal.from("0.1"), liquidPurchaseDiscount: Decimal.from("0.15"), illiquidPurchaseDiscount: Decimal.from("0.30"), liquidity: { volumeWeight: 1, stabilityWeight: 1, availabilityWeight: 1, volumeTarget: 20, availabilityTarget: 20, lowAt: 20, mediumAt: 40, liquidAt: 60, veryLiquidAt: 80 }, minimumOfferAction: "FLOOR", ...overrides } });
const point = (amount: string, daysAgo = 0, volume = 20, availability = 20, currency: "BRL" | "CNY" = "BRL"): MarketDataPoint => ({ skinVariantId: "ak-redline", price: money(amount, currency), observedAt: new Date(now.getTime() - daysAgo * 86400000), volume, availability });
const engine = (points: readonly MarketDataPoint[], rate = "0.72") => new PricingEngine(new MockMarketDataProvider(points), new MockExchangeRateProvider([{ baseCurrency: "CNY", quoteCurrency: "BRL", rate: Decimal.from(rate), observedAt: now, provider: "mock" }]));

test("inventory uses the current YouPin reference price before commercial adjustments", async () => { const result = await engine([point("10000")]).price({ operation: "INVENTORY", skinVariantId: "ak-redline", now, acquisitionCost: money("5000", "BRL") }, rule()); assert.equal(result.referencePrice.amount.toString(), "10000"); assert.equal(result.finalPrice.amount.toString(), "10000"); });
test("supplier order applies CNY × RMB/BRL × versioned markup", async () => { const result = await engine([point("5000", 0, 10, 10, "CNY")]).price({ operation: "ORDER", skinVariantId: "ak-redline", now }, rule()); assert.equal(result.finalPrice.amount.toString(), "3960"); assert.equal(result.pricingSnapshot.exchangeRate?.rate.toString(), "0.72"); });
test("liquid purchase uses its configured discount", async () => { const result = await engine([point("10000")]).price({ operation: "BUY", skinVariantId: "ak-redline", now }, rule()); assert.equal(result.pricingSnapshot.liquidity.band, "VERY_LIQUID"); assert.equal(result.finalPrice.amount.toString(), "8500"); });
test("non-liquid purchase uses its distinct configured discount", async () => { const result = await engine([point("10000", 0, 0, 0)]).price({ operation: "BUY", skinVariantId: "ak-redline", now }, rule()); assert.equal(result.pricingSnapshot.liquidity.band, "LOW"); assert.equal(result.finalPrice.amount.toString(), "7000"); });
test("seven-day market snapshot reports min max average median variation volatility and volume", () => { const snapshot = analyzeMarketHistory([point("10", 6, 1), point("20", 4, 2), point("30", 2, 3)], new Date(now.getTime() - 604800000), now); assert.equal(snapshot.minimum.amount.toString(), "10"); assert.equal(snapshot.maximum.amount.toString(), "30"); assert.equal(snapshot.average.amount.toString(), "20"); assert.equal(snapshot.median.amount.toString(), "20"); assert.equal(snapshot.variation.toString(), "2"); assert.equal(snapshot.totalVolume, 6); assert.equal(snapshot.volatility.isNegative(), false); });
test("liquidity score is bounded and categorized", () => { const snapshot = analyzeMarketHistory([point("100", 1, 40, 20), point("100", 0, 40, 20)], new Date(now.getTime() - 604800000), now); const assessment = assessLiquidity(snapshot, 20, rule().configuration.liquidity, "v1"); assert.equal(assessment.score, 100); assert.equal(assessment.band, "VERY_LIQUID"); });
test("risk margin protection floors a dangerous offer using configuration", async () => { const result = await engine([point("10000", 0, 0, 0)]).price({ operation: "BUY", skinVariantId: "ak-redline", now }, rule({ minimumOffer: money("8000", "BRL"), minimumOfferAction: "FLOOR" })); assert.equal(result.finalPrice.amount.toString(), "8000"); assert.equal(result.pricingSnapshot.decision, "FLOOR"); });
test("pricing snapshot records immutable inputs and output", async () => { const result = await engine([point("10000")]).price({ operation: "BUY", skinVariantId: "ak-redline", now }, rule()); assert.equal(Object.isFrozen(result.pricingSnapshot), true); assert.equal(result.pricingSnapshot.inputs.marketPrice, "10000"); assert.equal(result.pricingSnapshot.output.amount.toString(), "8500"); });
test("new rule versions do not mutate previously produced snapshots", async () => { const subject = engine([point("10000")]); const first = await subject.price({ operation: "BUY", skinVariantId: "ak-redline", now }, rule()); const second = await subject.price({ operation: "BUY", skinVariantId: "ak-redline", now }, { ...rule({ liquidPurchaseDiscount: Decimal.from("0.2") }), id: "price-rule-v2", version: 2 }); assert.equal(first.pricingSnapshot.ruleVersionId, "price-rule-v1"); assert.equal(first.finalPrice.amount.toString(), "8500"); assert.equal(second.finalPrice.amount.toString(), "8000"); });
test("the same inputs and rule version produce the same result", async () => { const subject = engine([point("10000")]); const request = { operation: "BUY" as const, skinVariantId: "ak-redline", now }; const [first, second] = await Promise.all([subject.price(request, rule()), subject.price(request, rule())]); assert.equal(first.finalPrice.amount.toString(), second.finalPrice.amount.toString()); assert.deepEqual(first.pricingSnapshot.inputs, second.pricingSnapshot.inputs); });
