import { Decimal, money, type Currency, type Money } from "../../pricing/src/index.ts";
export type LedgerType="CREDIT"|"DEBIT"|"HOLD"|"RELEASE"|"REFUND"|"PURCHASE"|"SALE"|"UPGRADE"|"DOWNGRADE"|"WITHDRAWAL"|"ADJUSTMENT";
export type PaymentStatus="PENDING"|"AUTHORIZED"|"PAID"|"FAILED"|"CANCELLED"|"REFUNDED"|"EXPIRED"|"UNDER_REVIEW";
export type OrderStatus="DRAFT"|"PENDING_PAYMENT"|"PAYMENT_CONFIRMED"|"AUTHORIZED"|"PROCESSING"|"SUPPLIER_ORDER_PENDING"|"SUPPLIER_ORDERED"|"ASSET_RECEIVED"|"DELIVERY_PENDING"|"COMPLETED"|"CANCELLED"|"REFUND_PENDING"|"REFUNDED"|"DISPUTED"|"UNDER_REVIEW";
export interface Wallet {id:string;userId:string;currency:Currency} export interface LedgerEntry {id:string;walletId:string;type:LedgerType;amount:Money;referenceType:string;referenceId:string;idempotencyKey:string;createdAt:Date;metadata?:Readonly<Record<string,string>>} export interface Hold {id:string;walletId:string;amount:Money;status:"ACTIVE"|"RELEASED"|"CAPTURED";idempotencyKey:string} export interface OrderItem {skinVariantId:string;quantity:number;unitPrice:Money;fees:Money;discount:Money;finalPrice:Money;pricingSnapshotId:string;source:"INVENTORY"|"ORDER";inventoryItemId?:string} export interface Order {id:string;userId:string;currency:Currency;status:OrderStatus;idempotencyKey:string;pricingSnapshotId:string;items:readonly OrderItem[]} export interface Payment {id:string;orderId:string;provider:string;providerPaymentId:string;amount:Money;status:PaymentStatus;idempotencyKey:string} export interface Refund {id:string;paymentId:string;amount:Money;status:"COMPLETED";idempotencyKey:string}
export interface PaymentProvider {readonly name:string;verifyWebhook(input:unknown):Promise<{providerEventId:string;paymentId:string;type:"PAID"|"FAILED";payload:Record<string,string>}>} export class MockPaymentProvider implements PaymentProvider {readonly name="mock";async verifyWebhook(input:unknown){return input as {providerEventId:string;paymentId:string;type:"PAID"|"FAILED";payload:Record<string,string>}}}
export interface LedgerIdempotencyStore { get(key:string): Promise<LedgerEntry|undefined>; set(key:string,entry:LedgerEntry): Promise<void> }
export class InMemoryLedgerIdempotencyStore implements LedgerIdempotencyStore { private readonly entries=new Map<string,LedgerEntry>();async get(key:string){return this.entries.get(key)}async set(key:string,entry:LedgerEntry){this.entries.set(key,entry)} }
export interface LedgerRepository { append(entry:LedgerEntry): Promise<void>; listByWallet(walletId:string): Promise<readonly LedgerEntry[]>; listAll(): Promise<readonly LedgerEntry[]> }
export class InMemoryLedgerRepository implements LedgerRepository { private readonly entries:LedgerEntry[]=[];async append(entry:LedgerEntry){this.entries.push(entry)}async listByWallet(walletId:string){return this.entries.filter(entry=>entry.walletId===walletId)}async listAll(){return [...this.entries]} }
export interface WalletRepository { getById(walletId:string): Promise<Wallet|undefined>; save(wallet:Wallet): Promise<Wallet> }
export class InMemoryWalletRepository implements WalletRepository { private readonly wallets=new Map<string,Wallet>();async getById(walletId:string){return this.wallets.get(walletId)}async save(wallet:Wallet){this.wallets.set(wallet.id,wallet);return wallet} }
export interface HoldIdempotencyStore { get(key:string): Promise<Hold|undefined>; set(key:string,hold:Hold): Promise<void> }
export class InMemoryHoldIdempotencyStore implements HoldIdempotencyStore { private readonly holds=new Map<string,Hold>();async get(key:string){return this.holds.get(key)}async set(key:string,hold:Hold){this.holds.set(key,hold)} }
export interface HoldRepository { getById(holdId:string): Promise<Hold|undefined>; save(hold:Hold): Promise<Hold>; listActiveByWallet(walletId:string): Promise<readonly Hold[]>; count(): Promise<number> }
export class InMemoryHoldRepository implements HoldRepository { private readonly holds=new Map<string,Hold>();async getById(holdId:string){return this.holds.get(holdId)}async save(hold:Hold){this.holds.set(hold.id,hold);return hold}async listActiveByWallet(walletId:string){return [...this.holds.values()].filter(hold=>hold.walletId===walletId&&hold.status==="ACTIVE")}async count(){return this.holds.size} }
export interface OrderIdempotencyStore { get(key:string): Promise<Order|undefined>; set(key:string,order:Order): Promise<void> }
export class InMemoryOrderIdempotencyStore implements OrderIdempotencyStore { private readonly orders=new Map<string,Order>();async get(key:string){return this.orders.get(key)}async set(key:string,order:Order){this.orders.set(key,order)} }
export interface OrderRepository { getById(orderId:string): Promise<Order|undefined>; save(order:Order): Promise<Order> }
export class InMemoryOrderRepository implements OrderRepository { private readonly orders=new Map<string,Order>();async getById(orderId:string){return this.orders.get(orderId)}async save(order:Order){this.orders.set(order.id,order);return order} }
export interface PaymentIdempotencyStore { get(key:string): Promise<Payment|undefined>; set(key:string,payment:Payment): Promise<void> }
export class InMemoryPaymentIdempotencyStore implements PaymentIdempotencyStore { private readonly payments=new Map<string,Payment>();async get(key:string){return this.payments.get(key)}async set(key:string,payment:Payment){this.payments.set(key,payment)} }
export interface PaymentRepository { getById(paymentId:string): Promise<Payment|undefined>; save(payment:Payment): Promise<Payment> }
export class InMemoryPaymentRepository implements PaymentRepository { private readonly payments=new Map<string,Payment>();async getById(paymentId:string){return this.payments.get(paymentId)}async save(payment:Payment){this.payments.set(payment.id,payment);return payment} }
export interface PaymentEventDedupStore { has(providerEventId:string): Promise<boolean>; record(providerEventId:string): Promise<void> }
export class InMemoryPaymentEventDedupStore implements PaymentEventDedupStore { private readonly events=new Set<string>();async has(providerEventId:string){return this.events.has(providerEventId)}async record(providerEventId:string){this.events.add(providerEventId)} }
export interface RefundIdempotencyStore { get(key:string): Promise<Refund|undefined>; set(key:string,refund:Refund): Promise<void> }
export class InMemoryRefundIdempotencyStore implements RefundIdempotencyStore { private readonly refunds=new Map<string,Refund>();async get(key:string){return this.refunds.get(key)}async set(key:string,refund:Refund){this.refunds.set(key,refund)} }
export interface RefundRepository { getById(refundId:string): Promise<Refund|undefined>; save(refund:Refund): Promise<Refund>; listByPayment(paymentId:string): Promise<readonly Refund[]>; count(): Promise<number> }
export class InMemoryRefundRepository implements RefundRepository { private readonly refunds=new Map<string,Refund>();async getById(refundId:string){return this.refunds.get(refundId)}async save(refund:Refund){this.refunds.set(refund.id,refund);return refund}async listByPayment(paymentId:string){return [...this.refunds.values()].filter(refund=>refund.paymentId===paymentId)}async count(){return this.refunds.size} }
export interface InventoryReservation { itemId:string }
export interface InventoryReservationRepository { getByItemId(itemId:string): Promise<InventoryReservation|undefined>; reserve(reservation:InventoryReservation): Promise<void>; release(itemId:string): Promise<void> }
export class InMemoryInventoryReservationRepository implements InventoryReservationRepository { private readonly reservations=new Map<string,InventoryReservation>();async getByItemId(itemId:string){return this.reservations.get(itemId)}async reserve(reservation:InventoryReservation){if(this.reservations.has(reservation.itemId))throw Error("Inventory unavailable");this.reservations.set(reservation.itemId,reservation)}async release(itemId:string){this.reservations.delete(itemId)} }
export interface FinanceTransactionContext { readonly ledgerIdempotencyStore:LedgerIdempotencyStore; readonly holdIdempotencyStore:HoldIdempotencyStore; readonly orderIdempotencyStore:OrderIdempotencyStore; readonly paymentIdempotencyStore:PaymentIdempotencyStore; readonly paymentEventDedupStore:PaymentEventDedupStore; readonly refundIdempotencyStore:RefundIdempotencyStore; readonly ledgerRepository:LedgerRepository; readonly walletRepository:WalletRepository; readonly holdRepository:HoldRepository; readonly orderRepository:OrderRepository; readonly paymentRepository:PaymentRepository; readonly refundRepository:RefundRepository; readonly inventoryReservationRepository:InventoryReservationRepository }
export interface FinanceTransactionManager { run<T>(operation:(tx:FinanceTransactionContext)=>Promise<T>):Promise<T> }
/** Composition boundary for tests only; it shares dependencies but does not implement rollback or production atomicity. */
export class InMemoryFinanceTransactionManager implements FinanceTransactionManager { private readonly context:FinanceTransactionContext;constructor(context:FinanceTransactionContext){this.context=context}async run<T>(operation:(tx:FinanceTransactionContext)=>Promise<T>):Promise<T>{return await operation(this.context)} }
const freeze=<T>(x:T):T=>Object.freeze(x);
/** In-memory reference implementation. A database adapter must execute each mutation in one DB transaction with unique idempotency indexes/row locks. */
export class FinanceService {private readonly ledgerIdempotencyStore:LedgerIdempotencyStore;private readonly holdIdempotencyStore:HoldIdempotencyStore;private readonly orderIdempotencyStore:OrderIdempotencyStore;private readonly paymentIdempotencyStore:PaymentIdempotencyStore;private readonly paymentEventDedupStore:PaymentEventDedupStore;private readonly refundIdempotencyStore:RefundIdempotencyStore;private readonly ledgerRepository:LedgerRepository;private readonly walletRepository:WalletRepository;private readonly holdRepository:HoldRepository;private readonly orderRepository:OrderRepository;private readonly paymentRepository:PaymentRepository;private readonly refundRepository:RefundRepository;private readonly inventoryReservationRepository:InventoryReservationRepository;constructor(ledgerIdempotencyStore:LedgerIdempotencyStore,holdIdempotencyStore:HoldIdempotencyStore,orderIdempotencyStore:OrderIdempotencyStore,paymentIdempotencyStore:PaymentIdempotencyStore,paymentEventDedupStore:PaymentEventDedupStore,refundIdempotencyStore:RefundIdempotencyStore,ledgerRepository:LedgerRepository,walletRepository:WalletRepository,holdRepository:HoldRepository,orderRepository:OrderRepository,paymentRepository:PaymentRepository,refundRepository:RefundRepository,inventoryReservationRepository:InventoryReservationRepository){this.ledgerIdempotencyStore=ledgerIdempotencyStore;this.holdIdempotencyStore=holdIdempotencyStore;this.orderIdempotencyStore=orderIdempotencyStore;this.paymentIdempotencyStore=paymentIdempotencyStore;this.paymentEventDedupStore=paymentEventDedupStore;this.refundIdempotencyStore=refundIdempotencyStore;this.ledgerRepository=ledgerRepository;this.walletRepository=walletRepository;this.holdRepository=holdRepository;this.orderRepository=orderRepository;this.paymentRepository=paymentRepository;this.refundRepository=refundRepository;this.inventoryReservationRepository=inventoryReservationRepository}readonly audit:string[]=[];
async createWallet(w:Wallet){await this.walletRepository.save(freeze({...w}))} async balance(id:string){const w=await this.walletRepository.getById(id);if(!w)throw Error("Wallet missing");let b=Decimal.zero();for(const e of await this.ledgerRepository.listByWallet(id)){b=["CREDIT","REFUND","RELEASE"].includes(e.type)?b.add(e.amount.amount):b.subtract(e.amount.amount)}return money(b,w.currency)} async available(id:string){let b=(await this.balance(id)).amount;for(const h of await this.holdRepository.listActiveByWallet(id))b=b.subtract(h.amount.amount);return money(b,(await this.walletRepository.getById(id))!.currency)}
private async post(type:LedgerType,w:string,a:Money,rt:string,ri:string,key:string){const old=await this.ledgerIdempotencyStore.get(key);if(old)return old;if(a.amount.compare("0")<=0)throw Error("Positive amount required");const e=freeze({id:`le_${(await this.ledgerRepository.listAll()).length+1}`,walletId:w,type,amount:a,referenceType:rt,referenceId:ri,idempotencyKey:key,createdAt:new Date()});await this.ledgerRepository.append(e);await this.ledgerIdempotencyStore.set(key,e);this.audit.push(`WALLET_${type}`);return e} async credit(w:string,a:Money,k:string){return await this.post("CREDIT",w,a,"MANUAL",k,k)} async debit(w:string,a:Money,k:string){if((await this.available(w)).amount.compare(a.amount)<0)throw Error("Insufficient available balance");return await this.post("DEBIT",w,a,"MANUAL",k,k)} async hold(w:string,a:Money,k:string){const old=await this.holdIdempotencyStore.get(k);if(old)return old;if((await this.available(w)).amount.compare(a.amount)<0)throw Error("Insufficient available balance");const h=freeze({id:`h_${await this.holdRepository.count()+1}`,walletId:w,amount:a,status:"ACTIVE" as const,idempotencyKey:k});await this.holdRepository.save(h);await this.holdIdempotencyStore.set(k,h);this.audit.push("WALLET_HOLD");return h} async release(id:string,_key:string){const h=await this.holdRepository.getById(id);if(!h)throw Error("Hold missing");if(h.status!=="ACTIVE")return h;const n=freeze({...h,status:"RELEASED" as const});await this.holdRepository.save(n);this.audit.push("WALLET_RELEASE");return n} async capture(id:string,k:string){const h=await this.holdRepository.getById(id);if(!h)throw Error("Hold missing");if(h.status!=="ACTIVE")return h;const n=freeze({...h,status:"CAPTURED" as const});await this.holdRepository.save(n);await this.post("PURCHASE",h.walletId,h.amount,"HOLD",id,k);return n}
async createOrder(o:Order){const old=await this.orderIdempotencyStore.get(o.idempotencyKey);if(old)return old;const n=freeze({...o,items:Object.freeze(o.items.map(i=>freeze({...i})))});await this.orderRepository.save(n);await this.orderIdempotencyStore.set(n.idempotencyKey,n);this.audit.push("ORDER_CREATED");return n} async reserve(item:string){await this.inventoryReservationRepository.reserve({itemId:item})} async createPayment(p:Payment){const old=await this.paymentIdempotencyStore.get(p.idempotencyKey);if(old)return old;const n=freeze({...p,status:"PENDING" as const});await this.paymentRepository.save(n);await this.paymentIdempotencyStore.set(n.idempotencyKey,n);return n} async webhook(provider:PaymentProvider,input:unknown){const e=await provider.verifyWebhook(input);if(await this.paymentEventDedupStore.has(e.providerEventId))return "DUPLICATE";const p=await this.paymentRepository.getById(e.paymentId);if(!p)throw Error("Payment missing");await this.paymentEventDedupStore.record(e.providerEventId);await this.paymentRepository.save(freeze({...p,status:e.type}));const o=await this.orderRepository.getById(p.orderId);await this.orderRepository.save(freeze({...o!,status:e.type==="PAID"?"PAYMENT_CONFIRMED":"PENDING_PAYMENT"}));this.audit.push(e.type==="PAID"?"PAYMENT_CONFIRMED":"PAYMENT_FAILED");return "PROCESSED"} async refund(paymentId:string,a:Money,k:string){const old=await this.refundIdempotencyStore.get(k);if(old)return old;const p=await this.paymentRepository.getById(paymentId);if(!p||p.status!=="PAID"||a.currency!==p.amount.currency)throw Error("Invalid refund");const refunded=(await this.refundRepository.listByPayment(paymentId)).reduce((total,refund)=>total.add(refund.amount.amount),Decimal.zero());if(refunded.add(a.amount).compare(p.amount.amount)>0)throw Error("Invalid refund");const r=freeze({id:`r_${await this.refundRepository.count()+1}`,paymentId,amount:a,status:"COMPLETED" as const,idempotencyKey:k});await this.refundRepository.save(r);await this.refundIdempotencyStore.set(k,r);this.audit.push("REFUND_COMPLETED");return r} async cancel(id:string){const o=await this.orderRepository.getById(id);if(!o)throw Error("Order missing");const n=freeze({...o,status:"CANCELLED" as const});await this.orderRepository.save(n);this.audit.push("ORDER_CANCELLED");return n} async getOrder(i:string){return await this.orderRepository.getById(i)}async getPayment(i:string){return await this.paymentRepository.getById(i)}async getEntries(){return await this.ledgerRepository.listAll()}}
