import { Decimal, money, type Currency, type Money } from "../../pricing/src/index.ts";
export type LedgerType="CREDIT"|"DEBIT"|"HOLD"|"RELEASE"|"REFUND"|"PURCHASE"|"SALE"|"UPGRADE"|"DOWNGRADE"|"WITHDRAWAL"|"ADJUSTMENT";
export type PaymentStatus="PENDING"|"AUTHORIZED"|"PAID"|"FAILED"|"CANCELLED"|"REFUNDED"|"EXPIRED"|"UNDER_REVIEW";
export type OrderStatus="DRAFT"|"PENDING_PAYMENT"|"PAYMENT_CONFIRMED"|"AUTHORIZED"|"PROCESSING"|"SUPPLIER_ORDER_PENDING"|"SUPPLIER_ORDERED"|"ASSET_RECEIVED"|"DELIVERY_PENDING"|"COMPLETED"|"CANCELLED"|"REFUND_PENDING"|"REFUNDED"|"DISPUTED"|"UNDER_REVIEW";
export interface Wallet {id:string;userId:string;currency:Currency} export interface LedgerEntry {id:string;walletId:string;type:LedgerType;amount:Money;referenceType:string;referenceId:string;idempotencyKey:string;createdAt:Date;metadata?:Readonly<Record<string,string>>} export interface Hold {id:string;walletId:string;amount:Money;status:"ACTIVE"|"RELEASED"|"CAPTURED";idempotencyKey:string} export interface OrderItem {skinVariantId:string;quantity:number;unitPrice:Money;fees:Money;discount:Money;finalPrice:Money;pricingSnapshotId:string;source:"INVENTORY"|"ORDER";inventoryItemId?:string} export interface Order {id:string;userId:string;currency:Currency;status:OrderStatus;idempotencyKey:string;pricingSnapshotId:string;items:readonly OrderItem[]} export interface Payment {id:string;orderId:string;provider:string;providerPaymentId:string;amount:Money;status:PaymentStatus;idempotencyKey:string} export interface Refund {id:string;paymentId:string;amount:Money;status:"COMPLETED";idempotencyKey:string}
export interface PaymentProvider {readonly name:string;verifyWebhook(input:unknown):Promise<{providerEventId:string;paymentId:string;type:"PAID"|"FAILED";payload:Record<string,string>}>} export class MockPaymentProvider implements PaymentProvider {readonly name="mock";async verifyWebhook(input:unknown){return input as {providerEventId:string;paymentId:string;type:"PAID"|"FAILED";payload:Record<string,string>}}}
export interface LedgerIdempotencyStore { get(key:string): LedgerEntry|undefined; set(key:string,entry:LedgerEntry): void }
export class InMemoryLedgerIdempotencyStore implements LedgerIdempotencyStore { private readonly entries=new Map<string,LedgerEntry>();get(key:string){return this.entries.get(key)}set(key:string,entry:LedgerEntry){this.entries.set(key,entry)} }
export interface LedgerRepository { append(entry:LedgerEntry): void; listByWallet(walletId:string): readonly LedgerEntry[]; listAll(): readonly LedgerEntry[] }
export class InMemoryLedgerRepository implements LedgerRepository { private readonly entries:LedgerEntry[]=[];append(entry:LedgerEntry){this.entries.push(entry)}listByWallet(walletId:string){return this.entries.filter(entry=>entry.walletId===walletId)}listAll(){return [...this.entries]} }
export interface WalletRepository { getById(walletId:string): Wallet|undefined; save(wallet:Wallet): Wallet }
export class InMemoryWalletRepository implements WalletRepository { private readonly wallets=new Map<string,Wallet>();getById(walletId:string){return this.wallets.get(walletId)}save(wallet:Wallet){this.wallets.set(wallet.id,wallet);return wallet} }
export interface HoldIdempotencyStore { get(key:string): Hold|undefined; set(key:string,hold:Hold): void }
export class InMemoryHoldIdempotencyStore implements HoldIdempotencyStore { private readonly holds=new Map<string,Hold>();get(key:string){return this.holds.get(key)}set(key:string,hold:Hold){this.holds.set(key,hold)} }
export interface HoldRepository { getById(holdId:string): Hold|undefined; save(hold:Hold): Hold; listActiveByWallet(walletId:string): readonly Hold[]; count(): number }
export class InMemoryHoldRepository implements HoldRepository { private readonly holds=new Map<string,Hold>();getById(holdId:string){return this.holds.get(holdId)}save(hold:Hold){this.holds.set(hold.id,hold);return hold}listActiveByWallet(walletId:string){return [...this.holds.values()].filter(hold=>hold.walletId===walletId&&hold.status==="ACTIVE")}count(){return this.holds.size} }
export interface OrderIdempotencyStore { get(key:string): Order|undefined; set(key:string,order:Order): void }
export class InMemoryOrderIdempotencyStore implements OrderIdempotencyStore { private readonly orders=new Map<string,Order>();get(key:string){return this.orders.get(key)}set(key:string,order:Order){this.orders.set(key,order)} }
export interface PaymentIdempotencyStore { get(key:string): Payment|undefined; set(key:string,payment:Payment): void }
export class InMemoryPaymentIdempotencyStore implements PaymentIdempotencyStore { private readonly payments=new Map<string,Payment>();get(key:string){return this.payments.get(key)}set(key:string,payment:Payment){this.payments.set(key,payment)} }
export interface PaymentEventDedupStore { has(providerEventId:string): boolean; record(providerEventId:string): void }
export class InMemoryPaymentEventDedupStore implements PaymentEventDedupStore { private readonly events=new Set<string>();has(providerEventId:string){return this.events.has(providerEventId)}record(providerEventId:string){this.events.add(providerEventId)} }
export interface RefundIdempotencyStore { get(key:string): Refund|undefined; set(key:string,refund:Refund): void }
export class InMemoryRefundIdempotencyStore implements RefundIdempotencyStore { private readonly refunds=new Map<string,Refund>();get(key:string){return this.refunds.get(key)}set(key:string,refund:Refund){this.refunds.set(key,refund)} }
const freeze=<T>(x:T):T=>Object.freeze(x);
/** In-memory reference implementation. A database adapter must execute each mutation in one DB transaction with unique idempotency indexes/row locks. */
export class FinanceService {private readonly ledgerIdempotencyStore:LedgerIdempotencyStore;private readonly holdIdempotencyStore:HoldIdempotencyStore;private readonly orderIdempotencyStore:OrderIdempotencyStore;private readonly paymentIdempotencyStore:PaymentIdempotencyStore;private readonly paymentEventDedupStore:PaymentEventDedupStore;private readonly refundIdempotencyStore:RefundIdempotencyStore;private readonly ledgerRepository:LedgerRepository;private readonly walletRepository:WalletRepository;private readonly holdRepository:HoldRepository;constructor(ledgerIdempotencyStore:LedgerIdempotencyStore,holdIdempotencyStore:HoldIdempotencyStore,orderIdempotencyStore:OrderIdempotencyStore,paymentIdempotencyStore:PaymentIdempotencyStore,paymentEventDedupStore:PaymentEventDedupStore,refundIdempotencyStore:RefundIdempotencyStore,ledgerRepository:LedgerRepository,walletRepository:WalletRepository,holdRepository:HoldRepository){this.ledgerIdempotencyStore=ledgerIdempotencyStore;this.holdIdempotencyStore=holdIdempotencyStore;this.orderIdempotencyStore=orderIdempotencyStore;this.paymentIdempotencyStore=paymentIdempotencyStore;this.paymentEventDedupStore=paymentEventDedupStore;this.refundIdempotencyStore=refundIdempotencyStore;this.ledgerRepository=ledgerRepository;this.walletRepository=walletRepository;this.holdRepository=holdRepository}private orders=new Map<string,Order>();private payments=new Map<string,Payment>();private refunds=new Map<string,Refund>();private reserved=new Set<string>();readonly audit:string[]=[];
createWallet(w:Wallet){this.walletRepository.save(freeze({...w}))} balance(id:string){const w=this.walletRepository.getById(id);if(!w)throw Error("Wallet missing");let b=Decimal.zero();for(const e of this.ledgerRepository.listByWallet(id)){b=["CREDIT","REFUND","RELEASE"].includes(e.type)?b.add(e.amount.amount):b.subtract(e.amount.amount)}return money(b,w.currency)} available(id:string){let b=this.balance(id).amount;for(const h of this.holdRepository.listActiveByWallet(id))b=b.subtract(h.amount.amount);return money(b,this.walletRepository.getById(id)!.currency)}
private post(type:LedgerType,w:string,a:Money,rt:string,ri:string,key:string){const old=this.ledgerIdempotencyStore.get(key);if(old)return old;if(a.amount.compare("0")<=0)throw Error("Positive amount required");const e=freeze({id:`le_${this.ledgerRepository.listAll().length+1}`,walletId:w,type,amount:a,referenceType:rt,referenceId:ri,idempotencyKey:key,createdAt:new Date()});this.ledgerRepository.append(e);this.ledgerIdempotencyStore.set(key,e);this.audit.push(`WALLET_${type}`);return e} credit(w:string,a:Money,k:string){return this.post("CREDIT",w,a,"MANUAL",k,k)} debit(w:string,a:Money,k:string){if(this.available(w).amount.compare(a.amount)<0)throw Error("Insufficient available balance");return this.post("DEBIT",w,a,"MANUAL",k,k)} hold(w:string,a:Money,k:string){const old=this.holdIdempotencyStore.get(k);if(old)return old;if(this.available(w).amount.compare(a.amount)<0)throw Error("Insufficient available balance");const h=freeze({id:`h_${this.holdRepository.count()+1}`,walletId:w,amount:a,status:"ACTIVE" as const,idempotencyKey:k});this.holdRepository.save(h);this.holdIdempotencyStore.set(k,h);this.audit.push("WALLET_HOLD");return h} release(id:string,_key:string){const h=this.holdRepository.getById(id);if(!h)throw Error("Hold missing");if(h.status!=="ACTIVE")return h;const n=freeze({...h,status:"RELEASED" as const});this.holdRepository.save(n);this.audit.push("WALLET_RELEASE");return n} capture(id:string,k:string){const h=this.holdRepository.getById(id);if(!h)throw Error("Hold missing");if(h.status!=="ACTIVE")return h;const n=freeze({...h,status:"CAPTURED" as const});this.holdRepository.save(n);this.post("PURCHASE",h.walletId,h.amount,"HOLD",id,k);return n}
createOrder(o:Order){const old=this.orderIdempotencyStore.get(o.idempotencyKey);if(old)return old;const n=freeze({...o,items:Object.freeze(o.items.map(i=>freeze({...i})))});this.orders.set(n.id,n);this.orderIdempotencyStore.set(n.idempotencyKey,n);this.audit.push("ORDER_CREATED");return n} reserve(item:string){if(this.reserved.has(item))throw Error("Inventory unavailable");this.reserved.add(item)} createPayment(p:Payment){const old=this.paymentIdempotencyStore.get(p.idempotencyKey);if(old)return old;const n=freeze({...p,status:"PENDING" as const});this.payments.set(n.id,n);this.paymentIdempotencyStore.set(n.idempotencyKey,n);return n} async webhook(provider:PaymentProvider,input:unknown){const e=await provider.verifyWebhook(input);if(this.paymentEventDedupStore.has(e.providerEventId))return "DUPLICATE";const p=this.payments.get(e.paymentId);if(!p)throw Error("Payment missing");this.paymentEventDedupStore.record(e.providerEventId);this.payments.set(p.id,freeze({...p,status:e.type}));const o=this.orders.get(p.orderId)!;this.orders.set(o.id,freeze({...o,status:e.type==="PAID"?"PAYMENT_CONFIRMED":"PENDING_PAYMENT"}));this.audit.push(e.type==="PAID"?"PAYMENT_CONFIRMED":"PAYMENT_FAILED");return "PROCESSED"} refund(paymentId:string,a:Money,k:string){const old=this.refundIdempotencyStore.get(k);if(old)return old;const p=this.payments.get(paymentId);if(!p||p.status!=="PAID"||a.currency!==p.amount.currency||a.amount.compare(p.amount.amount)>0)throw Error("Invalid refund");const r=freeze({id:`r_${this.refunds.size+1}`,paymentId,amount:a,status:"COMPLETED" as const,idempotencyKey:k});this.refunds.set(r.id,r);this.refundIdempotencyStore.set(k,r);this.audit.push("REFUND_COMPLETED");return r} cancel(id:string){const o=this.orders.get(id);if(!o)throw Error("Order missing");const n=freeze({...o,status:"CANCELLED" as const});this.orders.set(id,n);this.audit.push("ORDER_CANCELLED");return n} getOrder(i:string){return this.orders.get(i)}getPayment(i:string){return this.payments.get(i)}getEntries(){return this.ledgerRepository.listAll()}}
