import { PrismaClient, Prisma } from "@prisma/client";
export { PrismaWalletRepository, type WalletPrismaClient, type WalletPrismaDelegate, type WalletPrismaWallet, type WalletPrismaWalletUpdate } from "./wallet-repository.ts";
export { PrismaLedgerRepository, toDomainLedgerEntry, type LedgerDomainEntry, type LedgerPrismaClient, type LedgerPrismaCreate, type LedgerPrismaDelegate, type LedgerPrismaEntry, type LedgerType } from "./ledger-repository.ts";
export { PrismaLedgerIdempotencyStore, type LedgerIdempotencyClaim, type LedgerIdempotencyPrismaClient, type LedgerIdempotencyPrismaDelegate, type LedgerIdempotencyPrismaRecord } from "./ledger-idempotency-store.ts";
export { PrismaHoldRepository, toDomainHold, type HoldDomain, type HoldPrismaClient, type HoldPrismaCreate, type HoldPrismaDelegate, type HoldPrismaRow, type HoldPrismaUpdate, type HoldStatus } from "./hold-repository.ts";
export { createPrismaCaptureTransactionResources, type PrismaCaptureTransactionClient, type PrismaCaptureTransactionResources } from "./capture-transaction-resources.ts";
export { PrismaCaptureTransactionManager, type PrismaCaptureTransactionRunner } from "./capture-transaction-manager.ts";
export { PrismaClient, Prisma };
let client: PrismaClient | undefined;
export const getPrisma = (): PrismaClient => (client ??= new PrismaClient());
export const disconnectPrisma = async (): Promise<void> => { if (client) { await client.$disconnect(); client = undefined; } };
export const withTransaction = async <T>(work: (tx: Prisma.TransactionClient) => Promise<T>): Promise<T> => getPrisma().$transaction(work);
